
[general]
	#Puts all the added items into a new Every Compat tab instead of their own mod tabs. Be warned that if disabled it could cause some issue with some mods that have custom tabs
	creative_tab = true
	#Makes dynamic assets that are generated depend on loaded resource packs. Turn off to make them just use vanilla assets
	assets_depend_on_loaded_packs = true
	#Creates a debug folder inside your instance directory where all the dynamically generated resources will be saved
	save_debug_resources = false
	#Don't touch unless you are told to
	debug_packet = false

	[general.tooltips]
		#Enabled tooltips showing which mod an EC item is from
		mod_origin_enabled = true
		#Enabled tooltips showing which block type an EC item is made from
		block_type_enabled = true
		#Only show on advanced settings
		show_on_advanced_tooltips = false

	[general.types]

		[general.types.leaves_type]

			[general.types.leaves_type.ars_nouveau]
				blue_archwood = true
				green_archwood = true
				purple_archwood = true
				red_archwood = true

			[general.types.leaves_type.chipped]
				apple_acacia = true
				cherry_acacia = true
				dead_acacia = true
				frosted_acacia = true
				golden_acacia = true
				golden_apple_acacia = true
				golden_cherry_acacia = true
				magenta_flower_acacia = true
				orange_acacia = true
				red_acacia = true
				white_flower_acacia = true
				apple_birch = true
				cherry_birch = true
				dead_birch = true
				frosted_birch = true
				golden_birch = true
				golden_apple_birch = true
				golden_cherry_birch = true
				magenta_flower_birch = true
				orange_birch = true
				red_birch = true
				white_flower_birch = true
				apple_dark_oak = true
				cherry_dark_oak = true
				dead_dark_oak = true
				frosted_dark_oak = true
				golden_dark_oak = true
				golden_apple_dark_oak = true
				golden_cherry_dark_oak = true
				magenta_flower_dark_oak = true
				orange_dark_oak = true
				red_dark_oak = true
				white_flower_dark_oak = true
				apple_jungle = true
				cherry_jungle = true
				dead_jungle = true
				frosted_jungle = true
				golden_jungle = true
				golden_apple_jungle = true
				golden_cherry_jungle = true
				magenta_flower_jungle = true
				orange_jungle = true
				red_jungle = true
				white_flower_jungle = true
				apple_oak = true
				cherry_oak = true
				dead_oak = true
				frosted_oak = true
				golden_oak = true
				golden_apple_oak = true
				golden_cherry_oak = true
				magenta_flower_oak = true
				orange_oak = true
				red_oak = true
				white_flower_oak = true
				apple_spruce = true
				cherry_spruce = true
				dead_spruce = true
				frosted_spruce = true
				golden_spruce = true
				golden_apple_spruce = true
				golden_cherry_spruce = true
				magenta_flower_spruce = true
				orange_spruce = true
				red_spruce = true
				white_flower_spruce = true

			[general.types.leaves_type.vinery]
				grapevine = true
				cherry = true
				apple = true

		[general.types.wood_type]

			[general.types.wood_type.domum_ornamentum]
				cactus = true
				cactus_extra = true

			[general.types.wood_type.ars_nouveau]
				archwood = true

	[general.entries]

		[general.entries.leaves_type]

			[general.entries.leaves_type.mcwfences]
				hedge = true

			[general.entries.leaves_type.cfm]
				hedge = true

		[general.entries.wood_type]

			[general.entries.wood_type.cfm]
				stripped_kitchen_sink_light = true
				coffee_table = true
				stripped_kitchen_counter = true
				stripped_bedside_cabinet = true
				desk_cabinet = true
				kitchen_counter = true
				upgraded_gate = true
				crate = true
				stripped_blinds = true
				bedside_cabinet = true
				stripped_cabinet = true
				desk = true
				stripped_kitchen_drawer = true
				kitchen_sink_dark = true
				stripped_desk_cabinet = true
				blinds = true
				stripped_desk = true
				stripped_coffee_table = true
				stripped_crate = true
				table = true
				park_bench = true
				upgraded_fence = true
				stripped_park_bench = true
				cabinet = true
				mail_box = true
				chair = true
				stripped_mail_box = true
				stripped_upgraded_fence = true
				kitchen_drawer = true
				stripped_table = true
				stripped_chair = true
				stripped_kitchen_sink_dark = true
				kitchen_sink_light = true
				stripped_upgraded_gate = true

			[general.entries.wood_type.chipped]
				fine_planks = true
				checkered_trapdoor = true
				tiled_door = true
				pegged_planks = true
				secret_door = true
				smooth_planks = true
				bared_glass = true
				ornate_bared_glass = true
				hewn_planks = true
				beach_door = true
				fine_vertical_planks = true
				diamond_bordered_glass = true
				distorted_trapdoor = true
				iron_barred_trapdoor = true
				whirlwind_planks = true
				large_diamond_glass_pane = true
				framed_planks = true
				square_glass = true
				vined_trapdoor = true
				barrel = true
				detailed_planks = true
				cobweb_trapdoor = true
				barred_trapdoor = true
				airy_trapdoor = true
				pressed_door = true
				planks_panel = true
				solid_trapdoor = true
				boarded_door = true
				meshed_trapdoor = true
				fancy_trapdoor = true
				paper_door = true
				basket_woven_planks = true
				enclosed_planks = true
				double_herringbone_planks = true
				crated_planks = true
				classic_windowed_trapdoor = true
				wickered_planks = true
				heavy_trapdoor = true
				laced_planks = true
				boxed_planks = true
				reinforced_crate = true
				large_diamond_glass = true
				snowflake_glass_pane = true
				bricky_planks = true
				slotted_trapdoor = true
				polished_planks = true
				ornate_bared_glass_pane = true
				wall_torch = true
				glass_door = true
				paneled_door = true
				leafy_trapdoor = true
				pointless_trapdoor = true
				planks_shavings = true
				windowed_trapdoor = true
				tile_windowed_door = true
				golden_barred_trapdoor = true
				overgrown_trapdoor = true
				overgrown_door = true
				windowed_door = true
				classic_trapdoor = true
				circle_glass = true
				torch = true
				screen_door = true
				crossed_planks = true
				cross_laced_planks = true
				railed_planks = true
				planks_mosaic = true
				circle_glass_pane = true
				versailles_planks = true
				woven_glass = true
				woven_trapdoor = true
				gated_door = true
				supported_door = true
				line_bared_glass_pane = true
				horizontal_lined_glass_pane = true
				line_bared_glass = true
				slanted_planks = true
				barred_door = true
				suspicious_trapdoor = true
				herringbone_planks = true
				vertically_railed_planks = true
				bared_glass_pane = true
				diamond_bordered_glass_pane = true
				tiled_planks = true
				dual_paneled_door = true
				square_glass_pane = true
				thin_planks = true
				warted_trapdoor = true
				horizontal_lined_glass = true
				natural_planks = true
				brick_bond_planks = true
				bordered_glass_pane = true
				sliding_door = true
				bordered_glass = true
				shack_door = true
				diagonal_planks = true
				crate = true
				nailed_planks = true
				cornered_planks = true
				shifted_planks = true
				vertical_planks = true
				fortified_door = true
				snowflake_glass = true
				heavy_door = true
				stacked_planks = true
				twisted_trapdoor = true
				diamond_planks = true
				woven_glass_pane = true

			[general.entries.wood_type.mcwroofs]
				top_roof = true
				lower_roof = true
				planks_roof = true
				steep_roof = true
				planks_top_roof = true
				planks_upper_steep_roof = true
				upper_steep_roof = true
				upper_lower_roof = true
				attic_roof = true
				planks_upper_lower_roof = true
				roof = true
				planks_attic_roof = true
				planks_steep_roof = true
				planks_lower_roof = true

			[general.entries.wood_type.mcwfurnitures]
				stripped_glass_table = true
				end_table = true
				stool_chair = true
				stripped_drawer_counter = true
				stripped_counter = true
				covered_desk = true
				stripped_modern_wardrobe = true
				stripped_covered_desk = true
				stripped_cupboard_counter = true
				stripped_triple_drawer = true
				stripped_chair = true
				stripped_modern_desk = true
				stripped_bookshelf_cupboard = true
				modern_wardrobe = true
				striped_chair = true
				stripped_large_drawer = true
				wardrobe = true
				modern_desk = true
				stripped_end_table = true
				drawer = true
				chair = true
				stripped_table = true
				double_drawer_counter = true
				drawer_counter = true
				counter = true
				table = true
				stripped_double_drawer = true
				lower_triple_drawer = true
				bookshelf = true
				stripped_wardrobe = true
				large_drawer = true
				stripped_desk = true
				stripped_lower_triple_drawer = true
				bookshelf_drawer = true
				double_drawer = true
				stripped_coffee_table = true
				stripped_striped_chair = true
				stripped_stool_chair = true
				cupboard_counter = true
				coffee_table = true
				glass_table = true
				stripped_double_drawer_counter = true
				lower_bookshelf_drawer = true
				stripped_lower_bookshelf_drawer = true
				stripped_bookshelf_drawer = true
				stripped_bookshelf = true
				modern_chair = true
				stripped_modern_chair = true
				bookshelf_cupboard = true
				desk = true
				stripped_double_wardrobe = true
				triple_drawer = true
				double_wardrobe = true
				stripped_drawer = true

			[general.entries.wood_type.mcwdoors]
				japanese2_door = true
				tropical_door = true
				barn_glass_door = true
				four_panel_door = true
				cottage_door = true
				swamp_door = true
				barn_door = true
				classic_door = true
				beach_door = true
				japanese_door = true
				stable_door = true
				modern_door = true
				nether_door = true
				stable_head_door = true
				western_door = true
				paper_door = true
				bamboo_door = true
				glass_door = true
				mystic_door = true
				bark_glass_door = true
				waffle_door = true

			[general.entries.wood_type.mcwbridges]
				bridge_pier = true
				rope_bridge = true
				log_bridge_middle = true
				log_bridge_stair = true
				rope_bridge_stair = true
				rail_bridge = true

			[general.entries.wood_type.mcwtrpdoors]
				swamp_trapdoor = true
				cottage_trapdoor = true
				classic_trapdoor = true
				bamboo_trapdoor = true
				barn_trapdoor = true
				four_panel_trapdoor = true
				barred_trapdoor = true
				ranch_trapdoor = true
				beach_trapdoor = true
				glass_trapdoor = true
				blossom_trapdoor = true
				tropical_trapdoor = true
				paper_trapdoor = true
				bark_trapdoor = true
				mystic_trapdoor = true
				barrel_trapdoor = true

			[general.entries.wood_type.mcwpaths]
				planks_path = true

			[general.entries.wood_type.mcwfences]
				picket_fence = true
				wired_fence = true
				pyramid_gate = true
				highley_gate = true
				stockade_fence = true
				horse_fence = true

			[general.entries.wood_type.farmersdelight]
				cabinet = true

			[general.entries.wood_type.twigs]
				table = true

			[general.entries.wood_type.decorative_blocks]
				beam = true
				seat = true
				palisade = true
				support = true

			[general.entries.wood_type.mcwlights]
				soul_tiki_torch = true
				tiki_torch = true

			[general.entries.wood_type.storagedrawers]
				full_drawers_2 = true
				full_drawers_4 = true
				full_drawers_1 = true
				half_drawers_1 = true
				half_drawers_4 = true
				half_drawers_2 = true
				trim = true

			[general.entries.wood_type.create]
				window_pane = true
				window = true

